### ISSUE TITLE
DWD-WEATHER GRAPH

### ISSUE THREAD

**Issue by errtro** [mwittig/pimatic-dwd-weather#2]
Hallo,
wenn man sich den Graphen einer Station (sagen wir 10641: OF-Wetterpark) über eine längere Zeit anschaut, dann fällt auf, dass einige der dargestellten	 Werte "Außreiser" haben. Sehr auffällig bei der relativen Feuchte um 07:30 und 19:30. Das liegt einfach daran, dass zu den verschiedenen Zeiten unterschiedliche Messwerte in einer Zeile stehen. Hier ein Beispiel:

```
05.11.2017, 18:30 Uhr STATION	HÖHE	LUFTD.	TEMP.	U%	RR30	DD	FF	FX	WETTER+WOLKEN	BÖEN
05.11.2017, 19:00 Uhr STATION	HÖHE	LUFTD.	TEMP.	T-MIN	T-MAX	U%	RR1	RR12	SSS	DD	FF	FX	WETTER+WOLKEN	BÖEN
05.11.2017, 18:00 Uhr STATION	HÖHE	LUFTD.	TEMP.	U%	RR1	DD	FF	FX	WETTER+WOLKEN	BÖEN
06.11.2017, 11:00 Uhr STATION	HÖHE	LUFTD.	TEMP.	U%	RR1	DD	FF	FX	WETTER+WOLKEN	BÖEN
06.11.2017, 07:00 Uhr STATION	HÖHE	LUFTD.	TEMP.	T-MIN	T-MAX	U%	RR1	RR12	SSS	DD	FF	FX	WETTER+WOLKEN	BÖEN
```
Man muss also im html-Dokument den Eintrag
```
<thead>
<tr>
<th scope="col" >STATION</th>
<th scope="col">H&Ouml;HE</th>
<th scope="col"><abbr title="Luftdruck">LUFTD.</abbr></th>
<th scope="col"><abbr title="Temperatur">TEMP.</abbr></th>
<th scope="col"><abbr title="Relative Luftfeuchte">U%</abbr></th>
<th scope="col"><abbr title="Niederschlag">RR1</abbr></th>
<th scope="col"><abbr title="Windrichtung">DD</abbr></th>
<th scope="col"><abbr title="Windgeschwindigkeit">FF</abbr></th>
<th scope="col"><abbr title="Windspitzen">FX</abbr></th>
<th scope="col">Wetter+Wolken</th>
<th scope="col">B&ouml;en</th>
</tr>
</thead>

```
auswerten, um die Messwerte ihrer Bedeutung richtig zuzuordnen.

Viele Grüße

Rudolf Tröller

Deutscher Wetterdienst
Geschäftsbereich Technische Infrastruktur
Abteilung Systeme und Betrieb
Referat Systembetreuung
Sachgebiet Meteorologischer Datenaustausch

Frankfurter Straße 135
63067 Offenbach am Main

**Comment by mwittig** [comment]
Hallo Herr Tröller,

vielen Dank für Ihren Fehlerbericht! 

Ich habe bereits einen entsprechenden Test aufgesetzt um das Problem nachzustellen.  Ich bin bisher davon ausgeangen, dass die auf der Webseite dargestellte Tabelle einen statischen Spaltenaufbau hat und nur einzelne Werte dort gelistet werden. Eventuell treten auch Abweichungen in den protokollierten Daten durch fehlende Werte ('--') auf. 

Viele Grüße
Marcus Wittig

**Comment by mwittig** [comment]
Vielen Dank nochmals für Ihren hilfreichen Fehlerbericht!

**Comment by errtro** [comment]
Hallo Herr Wittig,
Ihre Lösung ist fast richtig. Nur mit dem Niederschlag gibt es noch Probleme:

um 07:00 erscheint
`<th scope="col"><abbr title="Niederschlag">RR1</abbr></th>`
`<th scope="col"><abbr title="Niederschlag">RR12</abbr></th>`

um 19:00 erscheint
`<th scope="col"><abbr title="Niederschlag">RR1</abbr></th>`
`<th scope="col"><abbr title="Niederschlag">RR12</abbr></th>`

zu jeder Stunde + 30 Min (00:30, 01:30, 02:30,...) erscheint
`<th scope="col"><abbr title="Niederschlag">RR30</abbr></th>hh+30`

hier ist
`RR1: Niederschlagsmenge, einstündig, mm ist gleich Liter pro m²`
`RR12: Niederschlagsmenge, 12 stündig, 06 UTCbis 18 UTC in mm ist gleich Liter pro m² -> 19:00 Meldung`
`RR12: Niederschlagsmenge, 12 stündig, 18 UTC Vortag bis 06 UTC heute in mm ist gleich Liter pro m² -> 07:00 Meldung`
`RR30: Niederschlagsmenge, halbstündig, mm ist gleich Liter pro m²`

RR12 sollte also in Ihrem Programm nicht ausgewertet werden

Viele Grüße

Rudolf Tröller

**Comment by mwittig** [comment]
Hallo Herr Tröller, vielen Dank für den Hinweis! 
Den Wert RR1 muss ich dann noch halbieren um vergleichbare Werte zu erhalten (wenn ich von halbstündigen Werte ausgehe), richtig?

Viele Grüße
Marcus Wittig

**Comment by errtro** [comment]
Hallo Herr Wittig,
folgender Fall: es regnet an einer Station nur von 09:05 bis 09:25 5
mm.Dann wird um 09:30 5 mm Niederschlag (RR30) gemeldet.Und um 10:00
ebenfalls 5 mm (RR1).
Am besten Sie lassen auch RR30 weg.
Sicher haben Sie auch die die Zeile "um 19:00 MEZ oder 20:00 MESZ" im
vorigen Post bemerkt. Das liegt daran, dass bei allen Wetterdiensten
der Welt die Uhren in UTC ticken.
Viele GrüßeRudolf Tröller

**Comment by mwittig** [comment]
Hallo Herr Tröller, 

vielen Dank nochmals für Ihre wertvollen Anmerkungen. 
In der aktuellen Version habe nun auch die Auswertung der Werte für Niederschläge entsprechend angepasst. 

Viele Grüße
Marcus Wittig
